---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myproj
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceBlacklist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myproj-sre
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
